# Generated by Django 5.2 on 2025-04-21 11:00

import froala_editor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=300, unique=True)),
                ('project_description', froala_editor.fields.FroalaField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('github_link', models.CharField(max_length=1000)),
                ('featured_image', models.ImageField(upload_to='photos/project_category')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(related_name='projects', to='category.projectscategory')),
            ],
        ),
    ]
