# Generated by Django 5.2 on 2025-04-18 17:59

import froala_editor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=100)),
                ('summary', froala_editor.fields.FroalaField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=200)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='photos/resume')),
                ('linkedin_profile', models.CharField(blank=True, max_length=500, null=True)),
                ('git_hub_profile', models.CharField(blank=True, max_length=500, null=True)),
                ('personal_portfolio_or_website', models.CharField(blank=True, max_length=500, null=True)),
                ('twitter', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
