# Generated by Django 5.2 on 2025-04-19 03:36

import froala_editor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_field',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
