# Generated by Django 5.2 on 2025-04-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=models.CharField(default='Unknown', max_length=150),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='images/djangocentral_hero.svg', upload_to='photos/category_images'),
        ),
    ]
