# Generated by Django 5.2 on 2025-04-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_category_name_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='Unknown', max_length=100)),
                ('category_slug', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
