# Generated by Django 5.2 on 2025-04-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tags_remove_post_author_post_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
