"""
Django settings for PYBLOG project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from django.conf.global_settings import STATICFILES_DIRS

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ot(^(zya8%mcwmgtkk(uw+=yfbh5g(f%h#b!y--+#3t00fv(bl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'blog',
    'category',
    'comments',
    'ckeditor',
    'ckeditor_uploader',
    'froala_editor',
    'accounts',
    'projects',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'PYBLOG.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PYBLOG.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CKEDITOR_UPLOAD_PATH = 'photos/uploads/'

AUTH_USER_MODEL = 'accounts.CustomUser'

ARTICLE_PER_PAGE = 5

FROALA_EDITOR_OPTIONS = {
    'toolbarSticky': True,
    'toolbarButtons': {
        'moreText': {
            'buttons': [
                'bold', 'italic', 'underline', 'strikeThrough',
                'subscript', 'superscript', 'fontFamily', 'fontSize',
                'textColor', 'backgroundColor', 'clearFormatting'
            ],
            'buttonsVisible': 10
        },
        'moreParagraph': {
            'buttons': [
                'alignLeft', 'alignCenter', 'alignRight', 'alignJustify',
                'formatOL', 'formatUL', 'paragraphFormat', 'paragraphStyle',
                'lineHeight', 'outdent', 'indent', 'quote'
            ],
            'buttonsVisible': 10
        },
        'moreRich': {
            'buttons': [
                'insertLink', 'insertImage', 'insertVideo', 'insertFile',
                'insertTable', 'emoticons', 'specialCharacters', 'hr',
                'embedly', 'insertHTML'
            ],
            'buttonsVisible': 10
        },
        'moreMisc': {
            'buttons': [
                'undo', 'redo', 'fullscreen', 'selectAll', 'html',
                'codeView', 'help', 'print', 'getPDF', 'spellChecker',
                'trackChanges', 'comment'
            ],
            'buttonsVisible': 10
        }
    },
    'pluginsEnabled': [
        'align', 'charCounter', 'codeBeautifier', 'codeView',
        'colors', 'draggable', 'emoticons', 'entities', 'file',
        'fontFamily', 'fontSize', 'fullscreen', 'image', 'imageManager',
        'inlineStyle', 'inlineClass', 'lineBreaker', 'link', 'lists',
        'paragraphFormat', 'paragraphStyle', 'print', 'quickInsert',
        'quote', 'save', 'selectAll', 'specialCharacters', 'table',
        'url', 'video', 'wordPaste', 'help', 'codeBlock',
        'trackChanges', 'comment', 'markdown', 'embedly', 'getPDF', 'spellChecker'
    ],
    'codeMirror': True,
    'codeMirrorOptions': {
        'theme': 'monokai',
        'mode': 'python',
        'lineNumbers': True,
        'lineWrapping': True,
        'matchBrackets': True,
        'autoCloseBrackets': True,
    },
    'spellcheck': True,
    'language': 'en_us',
    'placeholderText': 'Write your awesome content here...',
    'heightMin': 500,
    'heightMax': 1000,
    'fontFamilySelection': True,
    'fontSizeSelection': True,
    'paragraphFormatSelection': True,
    'quickInsertTags': ['image', 'video', 'table', 'ol', 'ul', 'hr'],
    'imageUpload': True,
    'videoUpload': True,
    'tableInsertHelper': True,
    'toolbarStickyOffset': 50,
    'attribution': False,  # hide "Powered by Froala" if licensed
    'saveInterval': 5000,  # autosave every 5 seconds (if configured)
    'zIndex': 2005
}




# FROALA_EDITOR_OPTIONS = {
#     'toolbarButtons': [
#         'undo', 'redo', '|',
#         'bold', 'italic', 'underline', 'strikeThrough', 'subscript', 'superscript', '|',
#         'fontFamily', 'fontSize', 'textColor', 'backgroundColor', '|',
#         'inlineClass', 'inlineStyle', '|',
#         'paragraphFormat', 'paragraphStyle', '|',
#         'align', 'formatOL', 'formatUL', 'outdent', 'indent', 'quote', '|',
#         'insertLink', 'insertImage', 'insertVideo', 'insertFile', 'insertTable', '|',
#         'emoticons', 'specialCharacters', 'insertHR', 'selectAll', 'clearFormatting', '|',
#         'print', 'spellChecker', 'help', 'fullscreen', '|',
#         'html', 'codeView', 'insertCodeBlock', 'save', 'preview'
#     ],
#     'toolbarButtonsXS': 'toolbarButtons',  # Same for mobile
#     'pluginsEnabled': [
#         'align', 'charCounter', 'codeBeautifier', 'codeView', 'colors', 'draggable',
#         'emoticons', 'entities', 'file', 'fontFamily', 'fontSize', 'fullscreen', 'image',
#         'imageManager', 'inlineClass', 'inlineStyle', 'lineBreaker', 'link', 'lists',
#         'paragraphFormat', 'paragraphStyle', 'print', 'quickInsert', 'quote', 'save',
#         'table', 'url', 'video', 'wordPaste', 'spellChecker', 'specialCharacters',
#         'help', 'insertCodeBlock', 'selectAll'
#     ],
#     'codeMirror': True,
#     'codeMirrorOptions': {
#         'theme': 'monokai',
#         'mode': 'htmlmixed',
#         'lineNumbers': True,
#         'indentWithTabs': True,
#         'tabSize': 2
#     },
#     'imageUpload': True,
#     'fileUpload': True,
#     'videoUpload': True,
#     'heightMin': 400,
#     'heightMax': 800,
#     'quickInsertTags': ['image', 'table', 'ol', 'ul', 'hr'],
#     'fontFamilySelection': True,
#     'fontSizeSelection': True,
#     'spellcheck': True,
#     'direction': 'auto',  # Auto-detect LTR/RTL
#     'theme': 'gray',  # Other option: 'dark'
#     'attribution': False,
#     'placeholderText': 'Start writing your document here...'
# }


